### ISSUE TITLE
[PHPUnit 10] Abstract test classes cannot use *Test suffix

### ISSUE THREAD

**Issue by IonBazan** [rectorphp/rector-phpunit#132]
Since PHPUnit 10, it is not allowed to name abstract test classes with `*Test` suffix, for example: `abstract class MyBaseTest` should be renamed to `abstract class MyBaseTestCase`, etc.
Many existing projects use this naming convention and need refactoring.

Please note that base `*Test` and target `*TestCase` suffixes should be customizable (users may choose different suffixes in `phpunit.xml` using `<directory suffix="Test.php">`).

For reference: https://github.com/sebastianbergmann/phpunit/issues/4979

**Comment by TomasVotruba** [comment]
Sounds good. Go for it :+1:

**Comment by johanadivare** [comment]
@IonBazan are you going to work on this?

**Comment by johanadivare** [comment]
Hmm i dont know how to rename files with rector.

A rule looks something like this

Find abstract test classes (wich dont need to be `Test.php` as you mentioned if `<directory suffix="Test.php">` is set)

Rename class

Rename file (we should also update other files that use this class but that might already be fixed with renaming class)

**Comment by johanadivare** [comment]
Just found https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#updatefilenamebyclassnamefilesystemrector which could be usefull

**Comment by johanadivare** [comment]
Started working on it see https://github.com/rectorphp/rector-phpunit/pull/141
