### ISSUE TITLE
Fatal error when using AbstractRectorTestCase in PHP8

### ISSUE THREAD

**Issue by leighman** [rectorphp/rector-phpunit#21]
Rector 130b634b5e348554c3349ed3b3f52fa3d08bfb6e
PHPUnit 8.5

```
PHP Fatal error:  Declaration of Rector\Testing\PHPUnit\PlatformAgnosticAssertions::assertStringEqualsFile($expectedFile, $actualString, $message = ''): void must be compatible with PHPUnit\Framework\Assert::assertStringEqualsFile(string $expectedFile, string $actualString, string $message = '', bool $canonicalize = false, bool $ignoreCase = false): void in /var/www/html/vendor/rector/rector/packages/Testing/PHPUnit/AbstractTestCase.php on line 41
```

**Comment by TomasVotruba** [comment]
Hi, for testing compatible PHPUnit is needed.

Maybe we'll have to exclude abstract test case from scoper or have one test case for PHP 7 and one for PHP 8 code

**Comment by leighman** [comment]
Suppprted is PHPUnit 9?

**Comment by TomasVotruba** [comment]
It's about the removed scalar types from methods, so only PHPUnit version without types would work.

We're using rector-src to test in our internal rules:
https://github.com/rectorphp/rector-doctrine/blob/main/composer.json#L17

Not sure what the right solution is here. Any ideas?

**Comment by Bl00D4NGEL** [comment]
@TomasVotruba the problem doesn't seem to be related to the types but instead to missing parameters.
PHPUnit 9.x:
```php
public static function assertFileEquals(string $expected, string $actual, string $message = ''): void
```

While in PHPUnit 8.x and below:
```php
public static function assertFileEquals(string $expected, string $actual, string $message = '', bool $canonicalize = false, bool $ignoreCase = false): void
```

In order to "restore" backward compatibility we could re-add the option parameters $canonicalize and $ignoreCase. This would allow the users of rector (specificially AbstractRectorTestCase) to use PHPUnit versions lower than 9.x

Though the current version of rector requires PHPUnit ^9.5 anyway so this is a problem with older rector versions.
In previous versions (pre https://github.com/rectorphp/rector/commit/f197e257930dd71389156c7f946eef123c6ffccd#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34R51) rector would require ^8.5|^9.2 so this problem seems to be with older rector versions only.

**Comment by TomasVotruba** [comment]
I see. Yea, min PHPUnit 9.5 is required. Maybe this check could be added on Rector running test case in runtime exceptoin, but now sure where exactly.

**Comment by leighman** [comment]
Doesn't that make it really difficult for people to write custom rules in legacy projects? When we started using Rector we were on PHPUnit 7. It was the first thing we updated though so I guess point to the update rules in the exception :joy:

**Comment by TomasVotruba** [comment]
It is problematic indeed :slightly_smiling_face: 

See https://github.com/rectorphp/rector/issues/6709#issuecomment-929534848 and https://github.com/rectorphp/rector-src/pull/930

I haven't tested PHPUnit 7, but Rector 0.11.56 should solve this for PHPUnit 8 and PHPUnit 9 :+1:

**Comment by TomasVotruba** [comment]
Closing as https://github.com/rectorphp/rector-src/pull/930 resolved this
